### PR TITLE
Fix PyPI classifier

### PR DESCRIPTION
**Pull request by iurisilvio**

### CODE REVIEW

**Comment by revolunet** [comment]
Hi @iurisilvio looks like you took charge of uploading to Pypi right ?
could you please grant @yguarata to update the package too ?
thanks

**Comment by iurisilvio** [comment]
Sure! Added @yguarata as maintainer in PyPI. Is it the same username there?

**Comment by revolunet** [comment]
it is, thank you :+1:

**Comment by yguarata** [comment]
Thanks, guys!

**Pull request merged**
