### PR TITLE
#12: Python3: TypeError: must be str, not bytes when using fill_form 

### PR DESCRIPTION
**Pull request by pmartynov**
Adding support of py3 in pypdftk.py

### CODE REVIEW

**Comment by revolunet** [comment]
Nice thanks !
Does it break Python 2 compat ?

**Comment by brandonwbrown** [comment]
any chance of a merge on this? 
many thanks!

**Comment by brandonwbrown** [comment]
this is working on py3, btw

**Comment by revolunet** [comment]
working on this...

**Comment by revolunet** [comment]
hi,

i rebased this branch. could you please check if its ok for you ?

Also, two tests are not passing on python 3 : `test_fill_form` and `test_dump_data_fields`. if someone could take a look at that it would be 👍

**Comment by revolunet** [comment]
there's a new PR with these changes and it now works on py 2 and 3 thanks to @pmartynov and @JZL

If anyone wants to confirm all is ok before release : https://github.com/revolunet/pypdftk/pull/23

**Pull request closed without merging**
