### PR TITLE
Adding function to apply stamps in PDF.

### PR DESCRIPTION
**Pull request by yguarata**

### CODE REVIEW

**Comment by revolunet** [comment]
awesome man, thanks

**Comment by yguarata** [comment]
It would be very welcome if you could upload a new version in PyPi. I have some restrictions in my production server to use pip+git. Thank you in advance.

**Comment by revolunet** [comment]
do you know the process ?
i made it a few years ago but i dont remember
or, better, maybe its possible for me to give you rights to do it ?

**Comment by yguarata** [comment]
You can grant me the role of maintainer. To do this, you have to log in pypi and select the pypdftk project. At the top you'll see the 'roles' option. Then you add my login as maintainer: yguarata.

**Comment by revolunet** [comment]
In PyPi i read "Package Index Owner: iurisilvio" so i guess he uploaded it and pinged him to add you as maintainer

**Comment by yguarata** [comment]
thanks!

**Pull request merged**
